name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build environment
      shell: bash
      run: mkdir build

    - name: Initialize cmake
      shell: bash
      working-directory: ./build/
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build the application
      shell: bash
      working-directory: ./build/
      run: make
